language: java
jdk:
  - oraclejdk7
services:
  - mysql
  - postgresql
install: "mvn install -P-MediumTests -DskipTests=true"
before_script:
  - psql -U postgres < ./flyway-core/src/test/resources/migration/dbsupport/postgresql/createDatabase.sql
  - mysql < ./flyway-core/src/test/resources/migration/dbsupport/mysql/createDatabase.sql
script: "mvn verify -P-MediumTests -PEmbeededDBTestOnly"