language: java
jdk:
  - oraclejdk7
services:
  - mysql
  - postgresql
before_install:
  - sudo rm /etc/mavenrc
before_script:
  - psql -U postgres < ./flyway-core/src/test/resources/migration/dbsupport/postgresql/createDatabase.sql
  - mysql --verbose -uroot < ./flyway-core/src/test/resources/migration/dbsupport/mysql/createDatabase.sql
script: "mvn install -PNoCommercialDBTest -P-CommercialDBJars"
